# Settings for the app
app:
  # HTML Title
  title: Participatory Budgeting Oakland
  # Header name
  name: "Participatory Budgeting Oakland"
  # Meta description that will show up in Google search results
  meta_description: "_(Welcome!)"
  # Meta author that will show up in Google search results
  meta_author: HaxGeo.com

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# languages:
#   - code: en
#     label: I Speak English

#   - code: es
#     label: Hablo Español

#   - code: vi
#     label: tôi nói tiếng việt

map:
# Settings for map and layer configs
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true
  #  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 37.79997
      lng: -122.23721
    zoom: 15
    minZoom: 1
    maxZoom: 18

  layers:
    - id: osm
      url: http://{s}.osm.maptiles.xyz/{z}/{x}/{y}.png
      attribution: <a href="/page/terms">Terms and conditions</a> &copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Mapbox</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: satellite
      url: //api.tiles.mapbox.com/v4/smartercleanup.pe3o4gdn/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: dark
      url: //api.mapbox.com/styles/v1/smartercleanup/cis9wdf5h003w2xt6atlz48yh/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: 'Hello World'

    - id: districts
      type: json
      url: "https://raw.githubusercontent.com/smartercleanup/data/master/oakland-districts.geojson"
      popupContent: '{{name}}'
      rules:
    # LineString
      - condition: '"{{geometry.type}}" == "LineString"'
        style:
          color: "{{properties.stroke}}"
          opacity: '{{properties.stroke-opacity}}'
          weight: "{{properties.stroke-width}}"
    # Polygons
      - condition: '"{{geometry.type}}" == "Polygon"'
        style:
          shapeType: polygon
          fillColor: "{{properties.fill}}"
          fill: 'true'
          color: "{{properties.stroke}}"
          opacity: 0.7
          fillOpacity: '{{properties.fill-opacity}}'
          weight: "{{properties.stroke-width}}"

    - id: pboakland
      type: place
      slug: idea

# The values map the place type to map icons (defined below).
place_types:
  youth:
    label: _(Observation)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-youth.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-youth.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-youth.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  senior:
    label: _(Question)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-seniors.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-seniors.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-seniors.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  parks:
    label: _(Idea)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-parks.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-parks.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-parks.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  streets:
    label: _(Complaint)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-streets.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-e1264d.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-streets.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: '{{map.zoom}} >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-streets.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  health:
    label: _(Health and Safety)
    rules:
      - condition: '{{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-health.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: '{{map.zoom}} < 15'
        icon:
          iconUrl: /static/css/images/markers/marker-health.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: '{{map.zoom}} < 18'
        icon:
          iconUrl: /static/css/images/markers/marker-health.png
          iconSize: [18, 21.75]
          iconAnchor: [9, 21.75]

      - condition: '{{map.zoom}} >= 18'
        icon:
          iconUrl: /static/css/images/markers/marker-health.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]


# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  # A panel's icon is a icon's name taken from here:
  # https://fortawesome.github.io/Font-Awesome/icons/
  panels:
    - id: gis-layers
      icon: list
      view: GISLegendView
      title: _(Map Layers:)
      basemaps:
        - id: osm
          title: _(OpenStreetMap)
          visibleDefault: true
        - id: satellite
          title: _(Satellite View)
          visibleDefault: false
        - id: dark
          title: _(Dark)
          visibleDefault: false
      groupings:
        - id: grp-community
          title: _(Community Data)
          visibleDefault: true
          layers:
            - id: pboakland
              title: _(Community Reports)
              visibleDefault: true

            - id: districts
              title: _(Oakland districts)
              visibleDefault: true

    - id: ticker
      view: ActivityView
      icon: comments-o
      activity: true
      title: _(Activity Stream:)

    - id: reports_legend
      title: _(Community ideas:)
      view: LegendView
      icon: info-circle
      items:
        - title: _(Observations)
          image: /static/css/images/markers/marker-youth.png
          url: /filter/observation
        - title: _(Ideas)
          image: /static/css/images/markers/marker-parks.png
          url: /filter/idea
        - title: _(Questions)
          image: /static/css/images/markers/marker-seniors.png
          url: /filter/question
        - title: _(Complaints)
          image: /static/css/images/markers/marker-streets.png
          url: /filter/complaint

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: true
  add_button_label: _(Share your idea!)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(See full list)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)

  location_item_name: location


  #### begin dynamic form config ####
  place_detail:
    - category: youth
      includeOnForm: true
      name: location_type
      dataset: pboakland
      icon_url: /static/css/images/markers/marker-youth.png
      value: youth
      label: _(Youth Services)
      fields:
        - name: title
          type: text
          prompt: _(Title of your idea:)
          display_prompt: _(Title:)
          placeholder: _( )
          optional: false
        - name: description
          type: textarea
          prompt: _(What is your idea for how to improve our neighborhood?:)
          display_prompt: _( )
          placeholder: _(Ideas must be for a program, service, or infrastructure improvement benefiting low-to-moderate income communities in the district.)
          optional: false
        - name: private-phone
          type: text
          prompt: _(Your phone number:)
          display_prompt: _()
          placeholder: _(Your phone number will not appear on the map)
          optional: true
        - name: private-age
          type: text
          prompt: _(Your age:)
          display_prompt: _()
          placeholder: _(Your age will not appear on the map)
          optional: true
        - name: private-ethnicity
          type: radio_big_buttons
          annotation: _(Your ethnicity will not appear on the map)
          prompt: _(Your ethnicity:)
          display_prompt: _(Ethnicity:)
          content:
            - label: _(American Indian/Alaskan Native)
              value: indian-alaskan
            - label: _(Asian)
              value: asian
            - label: _(Black or African American)
              value: black
            - label: _(Hispanic or Latino/a)
              value: hispanic
            - label: _(Native Hawaiian or Pacific Islander)
              value: hawaiian-pacific
            - label: _(White)
              value: white
            - label: _(Other)
              value: other
          optional: true
        - name: private-income
          type: dropdown
          prompt: _(Your income:)
          annotation: _(Your income will not appear on the map)
          content:
            - label: _(Under $10,000)
              value: under-10k
            - label: _($10,000 - $14,999)
              value: 10k-15k
            - label: _($15,000 - $24,999)
              value: 15k-25k
            - label: _($25,000 - $34,999)
              value: 25k-35k
            - label: _($35,000 - $49,000)
              value: 35k-49k
            - label: _($50,000 - $74,999)
              value: 50k-75k
            - label: _($75,000 - $99,000)
              value: 75k-99k
            - label: _($100,000 - $149,000)
              value: 100k-149k
            - label: _($150,000 or more)
              value: 150k-or-more
          optional: false
        - name: volunteer
          type: binary_toggle
          prompt: _(I want to volunteer:)
          display_prompt: _(I want to volunteer:)
          content:
            - label: _(Yes)
              value: "yes"
            - label: _(No)
              value: "no"
          optional: true
    - category: senior
      includeOnForm: true
      name: location_type
      dataset: pboakland
      icon_url: /static/css/images/markers/marker-seniors.png
      value: senior
      label: _(Senior Services)
      fields:
        - name: title
          type: text
          prompt: _(Title of your question:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your question?)"
          display_prompt: _( )
          placeholder: _(Enter question...)
    - category: parks
      includeOnForm: true
      name: location_type
      dataset: pboakland
      icon_url: /static/css/images/markers/marker-parks.png
      value: parks
      label: _(Parks and Recreation)
      fields:
        - name: title
          type: text
          prompt: _(Title of your idea:)
          placeholder: _(Enter title...)
          display_prompt: _(Title:)
          optional: false
        - name: description
          type: textarea
          prompt: _(Describe your idea below:)
          display_prompt: "_( )"
          placeholder: _(Description...)
          optional: false
    - category: streets
      includeOnForm: true
      name: location_type
      dataset: pboakland
      icon_url: /static/css/images/markers/marker-streets.png
      value: streets
      label: _(Streets and Sidewalk)
      fields:
        - name: title
          type: text
          prompt: _(Title of your complaint:)
          placeholder: _(Enter title...)
          display_prompt: _(Title:)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your complaint?)"
          display_prompt: _( )
          placeholder: _(Description...)
          optional: false
    - category: health
      includeOnForm: true
      name: location_type
      dataset: pboakland
      icon_url: /static/css/images/markers/marker-health.png
      value: health
      label: _(Health and Safety)
      fields:
        - name: title
          type: text
          prompt: _(Title of your complaint:)
          placeholder: _(Enter title...)
          display_prompt: _(Title:)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your complaint?)"
          display_prompt: _( )
          placeholder: _(Description...)
          optional: false
  # define form elements that appear on every form here
  common_form_elements:
    - name: submitter_name
      type: text
      prompt: _(Your name)
      placeholder: _(Name)
      optional: true
    - name: private-submitter_email
      type: text
      prompt: _(Your Email)
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Receive email updates on your report)
        - key: size
          value: 30
    - name: my_image
      type: file
      prompt: _(Image)
      inputfile_label: _(Add an Image)
      optional: true
      attrs:
        - key: accept
          value: image/*
    - type: submit
      label: _(Submit!)

  #### end dynamic form config ####

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Guidelines)
    slug: background
    name: background
    hide_from_top_bar: false

  - title: _(Get involved)
    slug: getinvolved
    name: contribute
