# Settings for the app
app:
  # HTML Title
  title: Air.HeyDuwamish
  # Site Link
  link: Air.HeyDuwamish
  # Header name
  name: Air.HeyDuwamish
  # Meta description that will show up in Google search results
  meta_description: _(Duwamish Air!)
  # Meta author that will show up in Google search results
  meta_author: SmarterCleanup.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

languages:

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  geocoding_enabled: true # enable general geocoding features (ie geocoded place fields)
  geocoding_bar_enabled: false # add a geocode bar across the map
  geocode_bounding_box: [45.2, -125, 49.3, -116.4] # Including cushion
  cartodb_enabled: true

  counter: false
  counter_min: 0
  counter_max: 1000

  options:
    center:
      lat: 47.61345
      lng: -122.29843
    zoom: 11
    minZoom: 7
    maxZoom: 18
    maxBounds: [[45.2, -125], [49.3, -116.4]] # Including cushion
  layers:
    - url: //{s}.tiles.mapbox.com/v4/smartercleanup.m1b2emco/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      visible: true
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'


  # Map Layers

    # TODO: json types only work when we add them to our sidebar
    - id: esri-air
      url: //services.arcgis.com/qboYD3ru0louQq4F/arcgis/rest/services/Duwamish_061415/FeatureServer/0/query?f=geojson&geometry={%22xmin%22:-126,%22ymin%22:43.2,%22xmax%22:-114.4,%22ymax%22:51.3,%22spatialReference%22:{%22wkid%22:4326}}&geometryType=esriGeometryEnvelope&inSR=2926&outFields=*&outSR=4326
      type: json
      popupContent: '{{Comments}}'
      rules:
        # default point marker case
        - condition: 'true'
          icon:
            # iconUrl: /static/css/images/markers/triangle-2654d2.png
            iconUrl: /static/css/images/markers/marker-observation.png
            iconSize: [16, 16]
            iconAnchor: [8, 8]

    # TODO: This is not set up for real-time readings
    # - id: mapbox-pscaa
    #   # url: //a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
    #   url: //a.tiles.mapbox.com/v4/smartercleanup.njpe7ha8/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
    #   type: json
    #   description: _(Air Monitoring Stations by PSCAA)
    #   popupContent: '{{title}}'
    #   legend: true
    #   visible: true
    #   title: _(Air Monitoring)
    #   rules:

    #     # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "danger"'
    #     #   icon:
    #     #     iconUrl: /static/css/images/markers/marker-construction.png
    #     #     iconSize: [30, 30]
    #     #     iconAnchor: [15, 15]

    #     # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "park2"'
    #     #   icon:
    #     #     iconUrl: /static/css/images/markers/marker-treeheart.png
    #     #     iconSize: [40, 40]
    #     #     iconAnchor: [13, 13]

    #     # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "industrial"'
    #     #   icon:
    #     #     iconUrl: /static/css/images/markers/marker-industrial.png
    #     #     iconSize: [40, 40]
    #     #     iconAnchor: [20, 20]

    #     # - condition: '"{{geometry.type}}" == "Point" && "{{properties.marker-symbol}}" === "bicycle"'
    #     #   icon:
    #     #     iconUrl: /static/css/images/markers/marker-bike.png
    #     #     iconSize: [30, 30]
    #     #     iconAnchor: [15, 15]

    #     # default point marker case
    #     - condition: 'true'
    #       icon:
    #         iconUrl: /static/css/images/markers/dot-fa307d.png
    #         iconSize: [16, 16]
    #         iconAnchor: [8, 8]

    - id: restoration
      url: https://k7b7dyc4v3.execute-api.us-west-2.amazonaws.com/production/mapbox/landmarks?url=http://a.tiles.mapbox.com/v4/smartercleanup.k9dcl2i9/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      type: landmark

    - id: vision
      url: https://k7b7dyc4v3.execute-api.us-west-2.amazonaws.com/production/mapbox/landmarks?url=http://a.tiles.mapbox.com/v4/smartercleanup.mfigd1mf/features.json?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      type: landmark

    - id: cleanup
      type: cartodb
      url: "https://smartercleanup.cartodb.com/api/v2/viz/b369d508-c02b-11e5-9a08-0ecfd53eb7d3/viz.json"

      # Land Use
    - id: landuse
      type: cartodb
      url: "https://hdbig.cartodb.com/api/v2/viz/76d1e054-d5ed-11e5-bf91-0e5db1731f59/viz.json"
      opacity: 0.5

      # Green Seattle Partnership restoration phases
    - id: phases
      type: cartodb
      url: "https://gis206.cartodb.com/api/v2/viz/217a2e02-e729-11e5-9bd4-0e5db1731f59/viz.json"

      # WMS Original Flow
    - id: duwamish-original
      url: https://smartercleanup.cartodb.com/api/v2/viz/ab34ca50-c6fc-11e5-ba65-0ecd1babdde5/viz.json
      type: cartodb
      opacity: 0.4

      # Noxious Weeds
    - id: noxious-weeds
      type: cartodb
      url: "https://hdbig.cartodb.com/api/v2/viz/f9350ac8-d677-11e5-980b-0e5db1731f59/viz.json"
      opacity: 0.5

  # # Report filters

  #   - title: _(Rain gardens)
  #     shareabouts: true
  #     image: /static/css/images/markers/marker-observation.png
  #     url: /filter/raingarden
  #     external: true
  #     visible: true

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:

  georgetownZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [60, 60]
        iconAnchor: [30, 30]
    - condition: '{{map.zoom}} < 14'
      icon:
        iconSize: [7.5, 7.5]
        iconAnchor: [4, 4]
    - condition: '{{map.zoom}} < 16'
      icon:
        iconSize: [15, 15]
        iconAnchor: [8, 8]
    - condition: '{{map.zoom}} >= 16'
      icon:
        iconSize: [30, 30]
        iconAnchor: [15, 15]

  mapboxZoomStyle:
    - condition: '{{layer.focused}} === true'
      icon:
        iconSize: [50, 50]
        iconAnchor: [25, 25]
    - condition: '{{map.zoom}} < 16'
      icon:
        iconSize: [20, 20]
        iconAnchor: [10, 10]
    - condition: '{{map.zoom}} >= 16'
      icon:
        iconSize: [30, 30]
        iconAnchor: [15, 15]

  wetland:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-land_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-land_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-land_no-prog-or-dead.png
  park:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-parks_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-parks_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-parks_no-prog-or-dead.png

  school:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-qual_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-qual_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-qual_no-prog-or-dead.png

  police:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-safe_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-safe_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-safe_no-prog-or-dead.png

  rail:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-transp_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-transp_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-transp_no-prog-or-dead.png

  town-hall:
    zoomType: georgetownZoomStyle
    rules:
      - condition: '"{{properties.marker-color}}" == "a3e46b"'
        icon:
          iconUrl: /static/css/images/markers/marker-hist_comp.png

      - condition: '"{{properties.marker-color}}" == "f1f075"'
        icon:
          iconUrl: /static/css/images/markers/marker-hist_prog.png

      - condition: '"{{properties.marker-color}}" == "f86767"'
        icon:
          iconUrl: /static/css/images/markers/marker-hist_no-prog-or-dead.png

  mapbox:
    # Mapbox Points
    rules:
    # LineString
      - condition: '"{{geometry.type}}" == "LineString"'
        style:
          color: "{{properties.stroke}}"
          opacity: '{{properties.stroke-opacity}}'
          weight: "{{properties.stroke-width}}"
    # Polygons
      - condition: '"{{geometry.type}}" == "Polygon"'
        style:
          shapeType: polygon
          fillColor: "{{properties.fill}}"
          fill: 'true'
          color: "{{properties.stroke}}"
          opacity: 0.7
          fillOpacity: '{{properties.fill-opacity}}'
          weight: "{{properties.stroke-width}}"

  danger:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-construction.png

  park2:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-heart.png

  industrial:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-industrial.png

  bicycle:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-bike.png

  swimming:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-swimming.png

  theatre:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-art.png

  zoo:
    zoomType: mapboxZoomStyle
    rules:
      - condition: 'true'
        icon:
          iconUrl: /static/css/images/markers/marker-whale.png

  air_watch:
    label: _(air watch observation)
    rules:
      - condition: '"{{location_type}}" === "air_watch" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [18, 25]
          iconAnchor: [9, 25]

      - condition: '"{{location_type}}" === "air_watch" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [40, 50]
          iconAnchor: [20, 50]
          shadowSize: [40, 50]
          shadowAnchor: [10, 50]

# TODO: Create data visualization where a cluster represents it location type makeup
cluster:
  threshold: 100
  class_small: cluster-small
  class_large: cluster-large
  size_small: 40
  size_large: 60

# Sidebar and activity stream should be enabled and disabled together!
# note: sidebar is aka 'MasterLegend'
# TODO: Couple the sidebar and activity stream because the activity stream is a component of the sidebar
sidebar:
  enabled: true
  legend_enabled: true
  slug: filter-type
  # Layers are defined in the "map config" section
  panels:
    legend:
      title: _(Community Air Observations)
      items:
        - title: _(Air Watch observation)
          image: /static/css/images/markers/marker-observation.png
    gis_layers:
      title: _(Map Layers:)
      groupings:
        - id: grp-community
          title: _(Community Data)
          visibleDefault: false
          layers:
            - id: cleanup
              description: _(The EPA-approved cleanup plan for the river)
              title: _(River cleanup plan)
              visibleDefault: false

            - id: vision
              visibleDefault: false
              title: _(Community vision)
              description: _(Priority areas identified through community visioning projects)

            - id: restoration
              visibleDefault: false
              title: _(Restoration sites)
              description: _(Habitat restoration and community organizing)


            - id: esri-air
              visibleDefault: true
              title: _(air watches)
              description: _(air watch observations)

        - id: grp-land
          title: _(Land Data)
          visibleDefault: false
          layers:
              # Land Use
            - id: landuse
              title: _(Land use)
              description: _(Land use data from 2010)
              visibleDefault: false

              # Green Seattle Partnership restoration phases
            - id: phases
              title: _(Green Seattle partnership)
              description: _(Restoration phases from the Green Seattle Partnership)
              visibleDefault: false

              # Noxious Weeds
            - id: noxious-weeds
              title: _(Noxious Weeds)
              description: _(Invasive species of weeds)
              visibleDefault: false

        - id: grp-history
          title: _(Historical Data)
          visibleDefault: false
          layers:

              # WMS Original Flow
            - id: duwamish-original
              description: _(The original Duwamish River path)
              title: _(Original river path)
              visibleDefault: false

    ticker:
      title: _(Activity Stream:)

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  dataset_slug: report # default is 'place'
  adding_supported: true
  add_button_label: _(Add your air concern to the map)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show as a list)
  show_map_button_label: _(Back to the Map)
  action_text: _(added)
  title: _(Add your air concern to the map)
  action_text: _(added)
  anonymous_name: _(Anonymous)
  submit_button_label: _(Put it on the map!)

  location_item_name: Address

  items:
    - prompt: _(Rain garden location)
      type: geocoding
      name: private-rain_garden_address
      optional:
      attrs:
        - key: placeholder
          value: _(Please type full address, (will not be published))
        - key: size
          value: 30
    - prompt: _(Garden Name)
      label: _(Garden Name:)
      type: text
      name: rain_garden_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Garden Name)
        - key: size
          value: 30
    - prompt: _(Rain garden size (square feet))
      label: _(Rain garden size (square feet):)
      type: text
      name: rain_garden_size
      sticky: true
      attrs:
        - key: placeholder
          value: _(Approximate square footage?)
        - key: size
          value: 30
    - prompt: _(Size of contributing area)
      label: _(Size of contributing area:)
      type: text
      name: contributing_area
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(How large is the catchment area that drains to this rain garden?)
        - key: size
          value: 30
    - prompt: _(Description)
      label: _(Description:)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Any notes you want to add for others would be wonderful :))
    - name: location_type
      type: hidden
      value: raingarden
    - prompt: _(Primary sources)
      label: _(Sources:)
      type: checkbox-list
      name: sources
      attrs:
        - label: _(Roof)
          value: roof
        - label: _(Pavement)
          value: pavement
        - label: _(Other)
          value: other
    - prompt: _(Designer)
      label: _(Designer:)
      type: text
      name: designer
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Designed by?)
        - key: size
          value: 30
    - prompt: _(Installer)
      label: _(Installer:)
      type: text
      name: installer
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Installed by?)
        - key: size
          value: 30
    - prompt: _(Contributor's name)
      label: _(Contributor's name:)
      type: text
      name: contributor_name
      optional:
      sticky: true
      attrs:
        - key: placeholder
          value: _(Who should we give credit to?)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-contributor_email
      optional:
      sticky: true
      attrs:
        - key: required
          value: _(Your email address is kept private and will not be published)
        - key: size
          value: 30
    - prompt:
      inputfile_label: _(Please add an image)
      type: file
      name: my_image
      optional:
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Like)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Background)
    slug: background
    name: background

  - title: _(Contribute)
    slug: contribute
    name: contribute
