# Settings for the app
app:
  # HTML Title
  title: Village Vanguard
  # Header name
  name: "Village Vanguard"
  # Meta description that will show up in Google search results
  meta_description: "_(Welcome!)"
  # Meta author that will show up in Google search results
  meta_author: haxgeo.com

  # This should be set to the root of an api server from which you'd like to draw
  # permissions information for logged-in users. This value can be overridden
  # using the API_ROOT environment variable. Note the trailing slash.
  api_root: https://dev-api.heyduwamish.org/api/v2/

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# languages:
#   - code: en_US
#     label: I Speak English

#   - code: es
#     label: Hablo Español

#   - code: vi
#     label: tôi nói tiếng việt

map:
# Settings for map and layer configs
  geolocation_enabled: true
  geolocation_onload: false
  cartodb_enabled: true
  #  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [46.500, -124, 48.5, -119] # south, west, north, east

  options:
    center:
      lat: 40.78041
      lng: -73.94279
    zoom: 12
    minZoom: 1
    maxZoom: 18

  layers:
    - id: osm
      url: https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png
      attribution: <a href="/page/terms">Terms and conditions</a> &copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Mapbox</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: terrain
      type: basemap
      url: //stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.png
      maxZoom: 16

    - id: satellite
      url: //api.tiles.mapbox.com/v4/smartercleanup.pe3o4gdn/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoic21hcnRlcmNsZWFudXAiLCJhIjoiTnFhUWc2cyJ9.CqPJH-9yspIMudowQJx2Uw
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="//mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="//www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">.'

    - id: nyrp
      url: https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/nyrp
      type: place
      slug: report

    - id: nyrpfeatured
      url: https://dev-api.heyduwamish.org/api/v2/smartercleanup/datasets/nyrpfeatured
      type: place
      slug: featured

    # TODO: add real layer
    - id: transit
      type: wms
      url: https://geoserver.mapseed.org/geoserver/kc_sewers/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers: sewer

    # TODO: add real layer
    - id: biking
      type: wms
      url: https://geoserver.mapseed.org/geoserver/kc_sewers/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers: sewer

    # TODO: add real layer
    - id: community
      type: wms
      url: https://geoserver.mapseed.org/geoserver/kc_sewers/wms?
      version: 1.3.0
      format: image/png
      transparent: true
      layers: sewer

    # TODO: add real layer
    - id: heat-waves
      type: basemap
      url: //api.mapbox.com/styles/v1/sliob/cj9s94qct1tuz2rmdcxkew1s4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic2xpb2IiLCJhIjoiY2o5cjdzdDkyNmk2MzMzdDRoZXk3MnRucCJ9.SCk-tekIRwDE5BY7T2GZRw

    # TODO: add real layer
    - id: flood-zones
      type: basemap
      url: //{s}.tiles.mapbox.com/v3/jkeefe.map-dg0rv3jh/{z}/{x}/{y}.png

    - id: flood-zones
      type: basemap
      url: //{s}.tiles.mapbox.com/v3/jkeefe.map-dg0rv3jh/{z}/{x}/{y}.png

# The values map the place type to map icons (defined below).
place_types:
  observation:
    label: _(Observation)
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: 'this.map.zoom < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: 'this.map.zoom < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: 'this.map.zoom >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-observation.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  question:
    label: _(Question)
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: 'this.map.zoom < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: 'this.map.zoom < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: 'this.map.zoom >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-question.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  idea:
    label: _(Idea)
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: 'this.map.zoom < 11'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: 'this.map.zoom < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: 'this.map.zoom >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-idea.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  complaint:
    label: _(Complaint)
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          iconAnchor: [25, 60]
          shadowSize: [50, 60]
          shadowAnchor: [14, 60]

      - condition: 'this.map.zoom < 11'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [10, 12]
          iconAnchor: [5, 12]

      - condition: 'this.map.zoom < 16'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [15, 18]
          iconAnchor: [7.5, 18]

      - condition: 'this.map.zoom >= 16'
        icon:
          iconUrl: /static/css/images/markers/marker-complaint.png
          iconSize: [38, 46]
          iconAnchor: [19, 46]

  featured_place:
    rules:
      - condition: 'this.layer.focused === true'
        icon:
          iconSize: [50, 50]
          iconAnchor: [25, 25]
      - condition: 'this.map.zoom < 15'
        icon:
          iconUrl: /static/css/images/markers/marker-construction-dot.png
          iconSize: [10, 10]
          iconAnchor: [0, 0]
      - condition: 'this.map.zoom <= 18'
        icon:
          iconUrl: /static/css/images/markers/marker-construction.png
          iconSize: [30, 30]
          iconAnchor: [15, 15]

sidebar:
  enabled: true
  panels:
    - id: gis-layers
      basemaps:
        - id: osm
          icon: map-o
          title: _(Default)
          visibleDefault: true
        - id: satellite
          icon: map
          title: _(Satellite)
          visibleDefault: false
        - id: terrain
          icon: globe
          title: _(Terrain)
          visibleDefault: false
      groupings:
        - id: map-detail
          title: _(Map detail)
          layers:
            - id: transit
              icon: train
              title: _(Transit)
              visibleDefault: false
            - id: biking
              icon: bicycle
              title: _(Biking)
              visibleDefault: false
            - id: nyrp
              icon: map-marker
              title: _(Comments)
              visibleDefault: false
            - id: community
              icon: users
              title: _(Community)
              visibleDefault: false
        - id: climate-risks
          title: _(Map detail)
          layers:
            - id: heat-waves
              icon: thermometer-full
              title: _(Heat Waves)
              visibleDefault: false
            - id: flood-zones
              icon: shower
              title: _(Flood Zones)
              visibleDefault: false


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

  # Place Types

place:
  adding_supported: true
  add_button_label: _(Add a report to the map!)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(See All Reports)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Put it on the map!)

  location_item_name: location


  #### begin dynamic form config ####
  place_detail:
    - category: featured_place
      admin_only: true
      includeOnForm: true
      showMetadata: false
      suppressAttachments: true
      horizontal_rule: true
      name: location_type
      dataset: nyrpfeatured
      icon_url: /static/css/images/markers/marker-star.png
      value: featured_place
      label: _(Featured Site)
      fields:
        - name: published
          type: publishControl
        - name: geometry
          type: geometryToolbar
          content:
            - url: /static/css/images/markers/marker-star.png
            - url: /static/css/images/markers/marker-bike.png
            - url: /static/css/images/markers/marker-construction.png
            - url: /static/css/images/markers/marker-foodforest.png
            - url: /static/css/images/markers/marker-greenwall.png
            - url: /static/css/images/markers/marker-heart.png
            - url: /static/css/images/markers/marker-hist_comp.png
            - url: /static/css/images/markers/marker-hist_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-hist_prog.png
            - url: /static/css/images/markers/marker-land_comp.png
            - url: /static/css/images/markers/marker-land_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-land_prog.png
            - url: /static/css/images/markers/marker-transp_comp.png
            - url: /static/css/images/markers/marker-transp_no-prog-or-dead.png
            - url: /static/css/images/markers/marker-transp_prog.png
        - name: title
          type: text
          prompt: _(Title of this featured site:)
          display_prompt: _( )
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: richTextarea
          prompt: _(Background, timeline, and data:)
          display_prompt: _(Background, timeline, and data)
          placeholder: _( )
        - name: url-title
          type: url-title
          prompt: _(Choose a custom URL for this place:)
          placeholder: "my-new-featured-place"
          optional: true
        - name: private-submitter_email
          type: commonFormElement
        - name: submit
          type: commonFormElement
    - category: observation
      includeOnForm: true
      name: location_type
      dataset: nyrp
      icon_url: /static/css/images/markers/marker-observation.png
      value: observation
      label: _(Observation)
      fields:
        - name: title
          type: text
          prompt: _(Title of your observation:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: false
        - name: pollution_type
          type: checkbox_big_buttons
          prompt: _(Types of pollution seen:)
          display_prompt: _( )
          content:
            - label: _(Sewage)
              value: sewage
            - label: _(Tires)
              value: tires
            - label: _(Illegal dumpsite)
              value: dumpsite
            - label: _(Litter)
              value: litter
            - label: _(Other)
              value: other
          optional: true # NOTE: checkbox_big_button inputs have no validation
        - name: description
          type: textarea
          prompt: _(Description:)
          display_prompt: _( )
          placeholder: _(Enter description...)
          optional: false
        - name: submitter_name
          type: commonFormElement
        - name: private-submitter_email
          type: commonFormElement
        - name: my_image
          type: commonFormElement
        - name: submit
          type: commonFormElement

    - category: question
      includeOnForm: true
      name: location_type
      dataset: nyrp
      icon_url: /static/css/images/markers/marker-question.png
      value: question
      label: _(Question)
      fields:
        - name: title
          type: text
          prompt: _(Title of your question:)
          display_prompt: _(Title:)
          placeholder: _(Enter title...)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your question?)"
          display_prompt: _( )
          placeholder: _(Enter question...)
        - name: submitter_name
          type: commonFormElement
        - name: private-submitter_email
          type: commonFormElement
        - name: my_image
          type: commonFormElement
        - name: submit
          type: commonFormElement

    - category: idea
      includeOnForm: true
      name: location_type
      dataset: nyrp
      icon_url: /static/css/images/markers/marker-idea.png
      value: idea
      label: _(Idea)
      fields:
        - name: title
          type: text
          prompt: _(Title of your idea:)
          placeholder: _(Enter title...)
          display_prompt: _(Title:)
          optional: false
        - name: description
          type: textarea
          prompt: _(Describe your idea below:)
          display_prompt: "_( )"
          placeholder: _(Description...)
          optional: false
        - name: submitter_name
          type: commonFormElement
        - name: private-submitter_email
          type: commonFormElement
        - name: my_image
          type: commonFormElement
        - name: submit
          type: commonFormElement

    - category: complaint
      includeOnForm: true
      name: location_type
      dataset: nyrp
      icon_url: /static/css/images/markers/marker-complaint.png
      value: complaint
      label: _(Complaint)
      fields:
        - name: title
          type: text
          prompt: _(Title of your complaint:)
          placeholder: _(Enter title...)
          display_prompt: _(Title:)
          optional: false
        - name: description
          type: textarea
          prompt: "_(What's your complaint?)"
          display_prompt: _( )
          placeholder: _(Description...)
          optional: false
        - name: submitter_name
          type: commonFormElement
        - name: private-submitter_email
          type: commonFormElement
        - name: my_image
          type: commonFormElement
        - name: submit
          type: commonFormElement

  # define form elements that appear on every form here
  common_form_elements:
    submitter_name:
      type: text
      prompt: _(Your name)
      placeholder: _(Name)
      optional: true
    private-submitter_email:
      type: text
      prompt: _(Your Email)
      placeholder: _(Receive email updates on your report)
      optional: true
      sticky: true
    my_image:
      type: file
      prompt: _(Image)
      inputfile_label: _(Add an Image)
      optional: true
      attrs:
        - key: accept
          value: image/*
    submit:
      type: submit
      label: _(Put it on the map!)

  #### end dynamic form config ####

survey:
  submission_type: comments

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview

  - title: _(Background)
    slug: background
    name: background
    hide_from_top_bar: true

  - title: _(Get involved)
    slug: getinvolved
    name: contribute
